apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: kustomize-nginx
  openshift-example: "yes"
resources:
  - deployment.yml
  - service.yml
  - route.yml
configMapGenerator:
- name: index
  files:
  - index.html
