* This is a very  simple pod

** Check your current namespace

   Before creating objects in OpenShift or Kubernetes you should check
   the current namespace that you are using

   #+begin_src sh
oc project
   #+end_src

** Creating a simple pod from the command line

   #+begin_src sh
oc run -i -t ubi --image=registry.redhat.io/ubi8/ubi:8.3 --restart=Never --rm
   #+end_src

   #+RESULTS:

   - -i ... run interactivly
   - -t ... allocate a terminal
   - --restart=Never ... Do not restart this pod
   - --rm ... Delete resources after this pod exits

    Try this command again but this time remove the _--rm_ option

   #+begin_src sh
oc run -i -t ubi --image=registry.redhat.io/ubi8/ubi:8.3 --restart=Never
   #+end_src

   Check if there is still a pod resource after you exit the shell

   #+begin_src sh
oc get pods
   #+end_src

   When finished delete the pod with

   #+begin_src
oc delete pod ubi
   #+end_src

** Creating a simple pod via a yaml file

   create the simple pod with

   #+begin_src sh
oc create -f simple-pod.yml
  #+end_src

   run

   #+begin_src sh
oc get pods
   #+end_src

   to the list of running pods in the current namespace.

** A pod running two containers

   Take a look at advanced-pod.yml. Explain what you see.

   #+begin_src sh
oc create -f advanced-pod.yml
  #+end_src

   run

   #+begin_src sh
oc get pods
   #+end_src

   to the list of running pods in the current namespace.

* Cleanup

  Execute

  #+begin_src
../../utils/cleanup.sh
  #+end_src
