apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
spec:
  storageClassName: "" # add available storage class here
  accessModes:
    - ReadWriteOnce    # could also be ReadWriteMany, talk to your admin if in doubt
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
