apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: worldclockapi
  namespace: bookinfo
spec:
  hosts:
  - worldclockapi.com
  ports:
  - name: https
    number: 443
    protocol: TLS
  resolution: DNS
  location: MESH_EXTERNAL
