# Local variables:
# after-save-hook: org-md-export-to-markdown
# end:

* ArgoCD

  |--------------------------------------------------------------------------------|
  | :exclamation: For me ArgoCD currently only works with cluster-admin privileges |
  |--------------------------------------------------------------------------------|

     ArgoCD needs project admin rights in your namespace:

   #+begin_src sh
oc adm policy add-cluster-role-to-user cluster-admin -z argocd-argocd-application-controller
   #+end_src

** Create an ArgoCD instance in your project and try to login

   First we create a new ArgoCD instance in our namespace.

   Make sure you are in the correct namespace before executing this command!

   #+begin_src sh
oc apply -f argocd.yml
   #+end_src



   Extract the admin password and the route and login to ArgoCD

   #+begin_src sh
export ARGOCD_PASSWORD=$(oc get secrets -o jsonpath="{.data['admin\.password']}" argocd-cluster |base64 -d)
export ARGOCD_ROUTE=$(oc get route -o yaml argocd-server -o jsonpath={.spec.host})
   #+end_src

   Execute

   #+begin_src
 oc get argocd argocd -o jsonpath='{.status.phase}{"\n"}'
   #+end_src

   and wait for ArgoCD to become available.

   #+begin_src
argocd  login --insecure --username admin --password "$ARGOCD_PASSWORD"  "$ARGOCD_ROUTE"
   #+end_src



   Try to list the available projects:

   #+begin_src sh
argocd proj list
   #+end_src

   ArgoCD also support SSO authentication via Keycloak, see
   https://docs.openshift.com/container-platform/4.7/cicd/gitops/configuring-sso-for-argo-cd-on-openshift.html
   for more information.

   Another method of authentication is using ArgoCD [[https://www.openshift.com/blog/openshift-authentication-integration-with-argocd][DEX]]. Be aware that
   this is *not* supported by Red Hat.

**  Deploying a simple application

  Create an example application within ArgoCD

  #+begin_src
PROJECT=$(oc project -q)
argocd app create nginx-app --project default --repo https://github.com/rhatservices/openshift-examples.git --revision main --path advanced-concepts/04_argocd/application --dest-server https://kubernetes.default.svc --dest-namespace $PROJECT
  #+end_src

  What is the state of the ArgoCD application after creating the new app?

  #+begin_src
argocd app list
argocd app get nginx-app
  #+end_src

  Can you synchronize the app?
