apiVersion: v1
kind: Pod
items:
- apiVersion: v1
  kind: Pod
  metadata:
    labels:
      run: simple-pod
    name: simple-pod
  spec:
    containers:
    - image: registry.access.redhat.com/ubi8/ubi
      env:
      - name: USER
        valueFrom:
          configMapKeyRef:
            name: user
            key: user
      - name: SECRET
        valueFrom:
          secretKeyRef:
            name: geheim
            key: secret
      name: simple-pod
      command:
        - sh
        - -c
        - 'while true; do echo -e "hello $USER!\n your secret is $SECRET\n\n" && sleep 2; done'
