---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: malicious-pvc
  labels:
    openshift-example: "yes"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
