apiVersion: apps/v1
kind: Deployment
metadata:
  name: kustomize-example
  labels:
    purpose: example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        deployer: conschul
    spec:
      containers:
        - name: simple-pod
          image: quay-enterprise.apps.ocp-test.sv-services.at/cdp/cdp-ubi:0
          env:
            - name: USER
              valueFrom:
                configMapKeyRef:
                  name: user
                  key: user
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: geheim
                  key: secret
          command:
            - sh
            - -c
            - 'while true; do echo -e "hello $USER!\n your secret is $SECRET\n\n" && sleep 2; done'
