---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-unprivileged
  labels:
    app: nginx
    openshift-example: "yes"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        openshift-example: "yes"
    spec:
      containers:
      - name: nginx
        image: nginxinc/nginx-unprivileged:1.25.2
        ports:
        - containerPort: 8080
