apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
    openshift-example: true
  name: http-probe
spec:
  containers:
  - name: http-probe
    image: nginxinc/nginx-unprivileged:1.18
    livenessProbe:
      httpGet:
        path: /hello
        port: 8080
        httpHeaders:
        - name: Custom-Header
          value: Awesome
      initialDelaySeconds: 3
      periodSeconds: 3
