apiVersion: v1
kind: Pod
metadata:
  name: tcp-live-ready
  labels:
    app: tcp-live-ready
spec:
  containers:
  - name: tcp-live-ready
    image: nginxinc/nginx-unprivileged:1.18
    ports:
    - containerPort: 8080
    readinessProbe:
      tcpSocket:
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 10
    livenessProbe:
      tcpSocket:
        port: 8080
      initialDelaySeconds: 15
      periodSeconds: 20
