apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
    openshift-example: "yes"
  name: liveness-exec
spec:
  containers:
  - name: liveness
    image: registry.redhat.io/ubi8/ubi:8.3
    args:
    - /bin/sh
    - -c
    - touch /tmp/healthy; sleep 30; rm -rf /tmp/healthy; sleep 600
    livenessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 5
