apiVersion: apps/v1
kind: Deployment
metadata:
  name: quota-test-quaranteed
  labels:
    app: quota-test-quaranteed
    openshift-example: "yes"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quota-test-quaranteed
  template:
    metadata:
      labels:
        app: quota-test-quaranteed
        openshift-example: "yes"
    spec:
      containers:
        - image: registry.redhat.io/ubi8/ubi:8.3
          name: test-pod-quaranteed
          resources:
            limits:
              cpu: 300m
              memory: 100Mi
          command:
            - sh
            - -c
            - 'echo "hello world" && sleep infinity'
