apiVersion: v1
kind: ResourceQuota
metadata:
  name: object-counts
  labels:
    openshift-example: "yes"
spec:
  hard:
    pods: "2"
    configmaps: "10"
    persistentvolumeclaims: "4"
    replicationcontrollers: "20"
    secrets: "10"
    services: "10"
    services.loadbalancers: "2"
