apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: quota-edit
  labels:
    openshift-example: true
rules:
- apiGroups:
  - ""
  resources:
  - limitranges
  - resourcequotas
  - resourcequotas/status
  verbs:
  - create
  - update
  - patch
  - delete
