apiVersion: v1
kind: Pod
items:
- apiVersion: v1
  kind: Pod
  metadata:
    labels:
      app: label-test
      environment: development
    name: pod-b
  spec:
    containers:
    - image: registry.redhat.io/ubi8/ubi:8.3
      name: pod-b
      command:
        - sh
        - -c
        - 'echo "hello world" && sleep infinity'
