apiVersion: velero.io/v1
kind: Restore
metadata:
  generation: 7
  name: nginx-restore
  namespace: openshift-adp
spec:
  backupName: nginx-backup
  excludedResources:
  - nodes
  - events
  - events.events.k8s.io
  - backups.velero.io
  - restores.velero.io
  - resticrepositories.velero.io
  hooks: {}
  includedNamespaces:
  - '*'
