apiVersion: v1
kind: Pod
metadata:
  labels:
    run: curl-pod
  name: curl-pod
spec:
  containers:
  - image: registry.redhat.io/ubi8/ubi:8.3
    env:
      - name: MY_NAMESPACE_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
    name: curl-pod
    command:
      - sh
      - -c
      - 'while /bin/true; do curl http://nginx."$MY_NAMESPACE_NAME".svc.cluster.local:8080; sleep 1; done'
