apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
  name: nginx
  labels:
    openshift-example: "yes"
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: nginx
    weight: 100
  wildcardPolicy: None
