* A full example for exposing an applictation

  In this example we are going to deploy a pod running nginx.

** Create a configmap using index.html

   We also label the configmap with _openshift-example=true_

   #+begin_src sh
oc create configmap index --from-file=index.html
oc label configmap index openshift-example=yes
   #+end_src

** Create a new deployment using nginx

   #+begin_src sh
oc apply -f nginx-deployment-cm.yml
   #+end_src

   What kind of resource are created?

*** Test the deployment with curl and oc port-forward.

   When you start _oc port-forward_ will just sit there with no output
   and forwards the port. For running the second _curl_ command open a
   second shell on the *same* machine where _oc port-foward_ is
   running (or move the command to the background).

   #+begin_src sh
export PORT="80$(( $RANDOM % 89 + 10))"
oc port-forward deployment/nginx-deployment $PORT:8080
curl localhost:$PORT
   #+end_src

** Create a service for nginx

   #+begin_src sh
oc apply -f nginx-service.yml
   #+end_src

   Can you use curl to access the service?

   #+begin_src
oc create -f curl-pod.yml
   #+end_src

   What happens if you modify the configmap and curl the service again?

** Expose the service

   #+begin_src sh
oc expose svc nginx
   #+end_src

   What kind of resource gets created?

   #+begin_src sh
oc get route
   #+end_src

   Try to access the nginx application via the route

   #+begin_src sh
curl -v $(oc get route nginx -o jsonpath={.spec.host})
   #+end_src

** Expose the service via a SSL edge terminating route

   #+begin_src sh
oc create route edge nginx-ssl --service=nginx
   #+end_src

   What kind of resource is created?

   Can you take a look at the details of the resource?

   #+begin_src sh
oc get route
   #+end_src

   Try to access the nginx application via the encrypted route

   #+begin_src sh
curl -kv https://$(oc get route nginx-ssl -o jsonpath={.spec.host})
   #+end_src

** Cleanup

   Delete all resources created:

   #+begin_src sh
../../utils/cleanup.sh
   #+end_src
