apiVersion: v1
kind: Pod
metadata:
  labels:
    app: label-test
    environment: development
  name: pod-b
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: environment
                operator: In
                values:
                  - production
          topologyKey: kubernetes.io/hostname
  containers:
  - image: registry.redhat.io/ubi8/ubi:8.3
    name: pod-b
    command:
      - sh
      - -c
      - 'echo "hello world" && sleep infinity'
