apiVersion: v1
kind: Pod
items:
- apiVersion: v1
  kind: Pod
  metadata:
    labels:
      app: backend
      environment: production
      openshift-example: "yes"
    name: pod-a
  spec:
    containers:
    - image: registry.redhat.io/ubi8/ubi:8.3
      name: pod-a
      command:
        - sh
        - -c
        - 'echo "hello world" && sleep infinity'
