apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-deployment
  labels:
    app: simple
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple
  template:
    metadata:
      labels:
        app: simple
        environment: production
    spec:
      containers:
      - image: registry.redhat.io/ubi8/ubi:8.3
        name: simple-pod
        command:
        - sh
        - -c
        - 'echo "hello world" && sleep infinity'
