apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: example-pdb
  labels:
    openshift-example: yes
spec:
  minAvailable: 1
  selector:
    matchLabels:
      environment: production
