apiVersion: v1
kind: Pod
items:
- apiVersion: v1
  kind: Pod
  metadata:
    labels:
      app: backend
      environment: production
    name: pod
  spec:
    containers:
    - image: registry.redhat.io/ubi8/ubi:8.3
      name: pod
      command:
        - sh
        - -c
        - 'echo "hello world" && sleep infinity'
