apiVersion: v1
kind: Pod
metadata:
    labels:
      app: backend
      environment: production
      openshift-example: "yes"
    name: pod2
spec:
    containers:
    - image: registry.redhat.io/ubi8/ubi:8.3
      name: pod
      command:
        - sh
        - -c
        - 'echo "hello world" && sleep infinity'
