apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-noschedule
  labels:
    app: simple
    openshift-example: yes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple
  template:
    metadata:
      labels:
        app: simple
        environment: production
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: box
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: simple
      containers:
      - image: registry.redhat.io/ubi8/ubi:8.3
        name: simple-pod
        command:
        - sh
        - -c
        - 'echo "hello world" && sleep infinity'
